name: Scheduled Report
on:
  push:

  schedule:
    - cron: 1 * * * *
    - cron: 00 07 * * *
    - cron: 30 20 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    environment: report
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - run: npm install
      - run: npm run start
